#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile @screen_name")
        
     # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    if get_user_timeline(sys.argv[1], 50) is not None:
        for tweet in get_user_timeline(sys.argv[1], 50):
            # analyze word
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(score, "green"), end = " ")
                print(colored(tweet, "green"))
            elif score < 0.0:
                print(colored(score, "red"), end=" ")
                print(colored(tweet, "red"))
            else:
                print(colored(score, "yellow"), end=" ")
                print(colored(tweet, "yellow"))

if __name__ == "__main__":
    main()